"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import {
  loadGroupedPlaylists,
  saveGroupedPlaylists,
  type GroupedPlaylist,
  type Rule,
  type SpacingRule,
  type AudioFeatureRule,
  type SortRule,
} from "@/lib/grouped-playlists";
import { getPlaylistTracksClient, getPlaylistNames, type SimplifiedTrack } from "@/lib/spotify";
import RulesModal from "@/app/components/RulesModal";
import "../../playlist/[id]/style.css";

type Group = { id: string; name: string; playlistIds: string[] };

type TrackFeature = {
  tempo: number;
  danceability: number;
  acousticness: number;
} | null;

type TrackedTrack = SimplifiedTrack & { sourcePlaylistId: string };

type PlaylistStat = { count: number; durationMs: number };

const SEGMENT_COLORS = [
  "#1db954", "#3d87e4", "#f0a500", "#e25f5f", "#a855f7", "#14b8a6", "#f97316",
];

function DonutChart({
  segments,
  totalLabel,
  subtotalLabel,
  size = 232,
}: {
  segments: { value: number; color: string }[];
  totalLabel: string;
  subtotalLabel: string;
  size?: number;
}) {
  const center = size / 2;
  const strokeWidth = 32;
  const r = center - strokeWidth / 2 - 8;
  const circumference = 2 * Math.PI * r;
  const total = segments.reduce((s, seg) => s + seg.value, 0);
  if (total === 0) return null;

  let accumulated = 0;
  const computed = segments.map((seg) => {
    const fullLen = (seg.value / total) * circumference;
    const gap = segments.length > 1 ? 3 : 0;
    const segLen = Math.max(0, fullLen - gap);
    const dashOffset = -accumulated;
    accumulated += fullLen;
    return { color: seg.color, segLen, dashOffset };
  });

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <g style={{ transform: `rotate(-90deg)`, transformOrigin: `${center}px ${center}px` }}>
        <circle
          cx={center} cy={center} r={r}
          fill="none"
          stroke="rgba(255,255,255,0.06)"
          strokeWidth={strokeWidth}
        />
        {computed.map(({ color, segLen, dashOffset }, i) => (
          <circle
            key={i}
            cx={center} cy={center} r={r}
            fill="none"
            stroke={color}
            strokeWidth={strokeWidth}
            strokeLinecap="butt"
            strokeDasharray={`${segLen} ${circumference * 2}`}
            strokeDashoffset={dashOffset}
          />
        ))}
      </g>
      <text
        x={center} y={center - 7}
        textAnchor="middle"
        fill="rgba(255,255,255,0.55)"
        fontSize="11"
        fontFamily="inherit"
      >
        {subtotalLabel}
      </text>
      <text
        x={center} y={center + 13}
        textAnchor="middle"
        fill="rgba(255,255,255,0.9)"
        fontSize="15"
        fontWeight="700"
        fontFamily="inherit"
      >
        {totalLabel}
      </text>
    </svg>
  );
}

function formatDuration(ms: number) {
  const m = Math.floor(ms / 60000);
  const s = Math.floor((ms % 60000) / 1000).toString().padStart(2, "0");
  return `${m}:${s}`;
}

function timeSince(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return "just now";
}

async function pushToSpotify(
  accessToken: string,
  tracks: TrackedTrack[],
  playlistName: string,
  existingPlaylistId?: string
): Promise<{ playlistId: string }> {
  const headers = {
    Authorization: `Bearer ${accessToken}`,
    "Content-Type": "application/json",
  };

  let pid = existingPlaylistId;

  // Verify the linked playlist still exists
  if (pid) {
    const check = await fetch(
      `https://api.spotify.com/v1/playlists/${pid}?fields=id`,
      { headers }
    );
    if (!check.ok) pid = undefined; // deleted externally — create a new one
  }

  if (!pid) {
    const meRes = await fetch("https://api.spotify.com/v1/me", { headers });
    if (!meRes.ok) throw new Error("Could not fetch Spotify profile.");
    const me = await meRes.json();

    const createRes = await fetch(
      `https://api.spotify.com/v1/users/${me.id}/playlists`,
      {
        method: "POST",
        headers,
        body: JSON.stringify({
          name: playlistName,
          description: "Generated by Road Trip Mix",
          public: false,
        }),
      }
    );
    if (!createRes.ok) throw new Error("Could not create Spotify playlist.");
    pid = (await createRes.json()).id as string;
  }

  // Replace tracks in chunks of 100 (Spotify API limit)
  const uris = tracks.map((t) => `spotify:track:${t.id}`);

  const putRes = await fetch(`https://api.spotify.com/v1/playlists/${pid}/tracks`, {
    method: "PUT",
    headers,
    body: JSON.stringify({ uris: uris.slice(0, 100) }),
  });
  if (!putRes.ok) throw new Error("Could not update Spotify playlist tracks.");

  for (let i = 100; i < uris.length; i += 100) {
    await fetch(`https://api.spotify.com/v1/playlists/${pid}/tracks`, {
      method: "POST",
      headers,
      body: JSON.stringify({ uris: uris.slice(i, i + 100) }),
    });
  }

  return { playlistId: pid };
}

function formatTotalDuration(ms: number) {
  const totalMinutes = Math.floor(ms / 60000);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

function trackKey(t: SimplifiedTrack) {
  return `${t.name}::${t.artists[0]?.name ?? ""}`;
}

function applySpacing(tracks: TrackedTrack[], rule: SpacingRule): TrackedTrack[] {
  const result: TrackedTrack[] = [];
  const remaining = [...tracks];

  while (remaining.length > 0) {
    const recent = result.slice(-rule.n);
    const recentArtists = new Set(recent.flatMap((t) => t.artists.map((a) => a.name)));
    const recentAlbums = new Set(recent.map((t) => t.album.name));

    let placed = false;
    for (let i = 0; i < remaining.length; i++) {
      const track = remaining[i];
      const artistConflict = rule.applyToArtist && track.artists.some((a) => recentArtists.has(a.name));
      const albumConflict = rule.applyToAlbum && recentAlbums.has(track.album.name);
      if (!artistConflict && !albumConflict) {
        result.push(...remaining.splice(i, 1));
        placed = true;
        break;
      }
    }

    // No conflict-free track available — place the first remaining track anyway
    if (!placed) result.push(remaining.shift()!);
  }

  return result;
}

function applyAudioFeature(
  tracks: TrackedTrack[],
  rule: AudioFeatureRule,
  featureMap: Map<string, TrackFeature>
): TrackedTrack[] {
  const getValue = (t: SimplifiedTrack): number | null => {
    const f = featureMap.get(trackKey(t));
    if (!f) return null;
    switch (rule.feature) {
      case "tempo": return f.tempo > 0 ? f.tempo : null;
      case "danceability": return f.danceability;
      case "acousticness": return f.acousticness;
    }
  };

  const known = tracks.filter((t) => getValue(t) !== null);
  const missing = tracks.filter((t) => getValue(t) === null);

  if (rule.direction === "asc" || rule.direction === "desc") {
    known.sort((a, b) => {
      const va = getValue(a)!;
      const vb = getValue(b)!;
      return rule.direction === "asc" ? va - vb : vb - va;
    });
  } else {
    // "asc-desc": sort ascending, first half stays, second half reversed → mountain shape
    known.sort((a, b) => getValue(a)! - getValue(b)!);
    const peak = Math.ceil(known.length / 2);
    const down = known.splice(peak).reverse();
    known.push(...down);
  }

  switch (rule.missingPlacement) {
    case "first":
      return [...missing, ...known];
    case "last":
      return [...known, ...missing];
    case "alternate": {
      const result: TrackedTrack[] = [];
      let ki = 0, mi = 0;
      while (ki < known.length || mi < missing.length) {
        if (ki < known.length) result.push(known[ki++]);
        if (mi < missing.length) result.push(missing[mi++]);
      }
      return result;
    }
    case "disperse":
    case "disperse-start":
    case "disperse-end": {
      if (missing.length === 0) return known;
      if (known.length === 0) return missing;
      const total = known.length + missing.length;

      // Determine the zone [zoneStart, zoneStart + zoneLen) where missing tracks are spread
      let zoneStart = 0;
      let zoneLen = total;
      if (rule.missingPlacement === "disperse-start") {
        zoneLen = Math.ceil(total / 2);
      } else if (rule.missingPlacement === "disperse-end") {
        zoneLen = Math.ceil(total / 2);
        zoneStart = total - zoneLen;
      }

      const insertAt = new Set(
        Array.from({ length: missing.length }, (_, i) =>
          zoneStart + Math.round((0.5 + i) * zoneLen / missing.length)
        ).map((p) => Math.min(p, total - 1))
      );

      const result: TrackedTrack[] = [];
      let ki = 0, mi = 0;
      for (let i = 0; i < total; i++) {
        if (insertAt.has(i) && mi < missing.length) {
          result.push(missing[mi++]);
        } else if (ki < known.length) {
          result.push(known[ki++]);
        } else {
          result.push(missing[mi++]);
        }
      }
      while (ki < known.length) result.push(known[ki++]);
      while (mi < missing.length) result.push(missing[mi++]);
      return result;
    }
  }
}

// Simple but good-quality 32-bit hash for seeded shuffle
function seededRng(seed: number) {
  let s = seed | 0;
  return () => {
    s = Math.imul(s ^ (s >>> 16), 0x45d9f3b);
    s = Math.imul(s ^ (s >>> 16), 0x45d9f3b);
    s ^= s >>> 16;
    return (s >>> 0) / 0x100000000;
  };
}

function applySort<T extends SimplifiedTrack>(
  tracks: T[],
  rule: SortRule,
  featureMap: Map<string, TrackFeature> | null
): T[] {
  const result = [...tracks];

  switch (rule.method) {
    case "random":
      for (let i = result.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [result[i], result[j]] = [result[j], result[i]];
      }
      return result;

    case "random-seeded": {
      const rng = seededRng(rule.seed ?? 1);
      for (let i = result.length - 1; i > 0; i--) {
        const j = Math.floor(rng() * (i + 1));
        [result[i], result[j]] = [result[j], result[i]];
      }
      return result;
    }

    case "random-soft": {
      const w = Math.max(2, rule.window ?? 5);
      for (let i = 0; i < result.length - 1; i++) {
        const j = i + Math.floor(Math.random() * Math.min(w, result.length - i));
        [result[i], result[j]] = [result[j], result[i]];
      }
      return result;
    }

    case "name-asc":  return result.sort((a, b) => a.name.localeCompare(b.name));
    case "name-desc": return result.sort((a, b) => b.name.localeCompare(a.name));

    case "album-asc":  return result.sort((a, b) => a.album.name.localeCompare(b.album.name));
    case "album-desc": return result.sort((a, b) => b.album.name.localeCompare(a.album.name));

    case "artist-asc":
      return result.sort((a, b) => (a.artists[0]?.name ?? "").localeCompare(b.artists[0]?.name ?? ""));
    case "artist-desc":
      return result.sort((a, b) => (b.artists[0]?.name ?? "").localeCompare(a.artists[0]?.name ?? ""));

    case "bpm-asc":
    case "bpm-desc": {
      const bpm = (t: SimplifiedTrack) => featureMap?.get(trackKey(t))?.tempo ?? 0;
      return result.sort((a, b) => rule.method === "bpm-asc" ? bpm(a) - bpm(b) : bpm(b) - bpm(a));
    }

    case "duration-asc":  return result.sort((a, b) => a.duration_ms - b.duration_ms);
    case "duration-desc": return result.sort((a, b) => b.duration_ms - a.duration_ms);
  }
}

function applyRoundRobin(
  tracksByPlaylist: { playlistId: string; tracks: SimplifiedTrack[] }[],
  rules: Rule[]
): TrackedTrack[] {
  const tag = (t: SimplifiedTrack, pid: string): TrackedTrack => ({ ...t, sourcePlaylistId: pid });

  if (rules.length === 0 || tracksByPlaylist.length === 0) return [];

  const rule = rules.find((r) => r.type === "round_robin");
  if (!rule || rule.type !== "round_robin") {
    return tracksByPlaylist.flatMap((p) => p.tracks.map((t) => tag(t, p.playlistId)));
  }

  const queues = tracksByPlaylist.map((p) => ({
    playlistId: p.playlistId,
    tracks: p.tracks.map((t) => tag(t, p.playlistId)),
  }));
  const result: TrackedTrack[] = [];

  let anyLeft = true;
  while (anyLeft) {
    anyLeft = false;
    for (const queue of queues) {
      const n = rule.overrides[queue.playlistId] ?? rule.defaultN;
      for (let j = 0; j < n; j++) {
        const track = queue.tracks.shift();
        if (track) { result.push(track); anyLeft = true; }
      }
    }
  }
  return result;
}

async function fetchAudioFeatures(tracks: SimplifiedTrack[]): Promise<TrackFeature[]> {
  try {
    const res = await fetch("/api/audio-features", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tracks: tracks.map((t) => ({ name: t.name, artist: t.artists[0]?.name ?? "" })),
      }),
    });
    if (!res.ok) return tracks.map(() => null);
    const data = await res.json();
    return data.features ?? tracks.map(() => null);
  } catch {
    return tracks.map(() => null);
  }
}

export default function GroupedPlaylistClient({ id }: { id: string }) {
  const { data: session } = useSession();
  const [playlist, setPlaylist] = useState<GroupedPlaylist | null>(null);
  const [group, setGroup] = useState<Group | null>(null);
  const [groupPlaylists, setGroupPlaylists] = useState<{ id: string; name: string }[]>([]);
  const [playlistStats, setPlaylistStats] = useState<Map<string, PlaylistStat> | null>(null);
  const [loadingStats, setLoadingStats] = useState(false);
  const [showRules, setShowRules] = useState(false);
  const [generated, setGenerated] = useState<TrackedTrack[] | null>(null);
  const [generating, setGenerating] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [syncError, setSyncError] = useState<string | null>(null);

  // Restore previously generated tracks from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem(`road-trip-mix:generated:${id}`);
      if (saved) setGenerated(JSON.parse(saved));
    } catch {}
  }, [id]);

  useEffect(() => {
    const gps = loadGroupedPlaylists();
    const found = gps.find((p) => p.id === id) ?? null;
    setPlaylist(found);

    if (found) {
      try {
        const groups: Group[] = JSON.parse(localStorage.getItem("road-trip-mix:groups") ?? "[]");
        const g = groups.find((gr) => gr.id === found.groupId) ?? null;
        setGroup(g);
        if (g) {
          // Set IDs as placeholder names until Spotify lookup resolves
          setGroupPlaylists(g.playlistIds.map((pid) => ({ id: pid, name: pid })));
        }
      } catch {}
    }
  }, [id]);

  // Resolve human-readable playlist names once session is available
  useEffect(() => {
    if (!session?.accessToken || !group) return;
    getPlaylistNames(session.accessToken, group.playlistIds).then((nameMap) => {
      setGroupPlaylists(group.playlistIds.map((pid) => ({ id: pid, name: nameMap[pid] ?? pid })));
    });
  }, [session, group]);

  // Fetch per-playlist stats (track count + total duration) in background
  useEffect(() => {
    if (!session?.accessToken || !group) return;
    setLoadingStats(true);
    Promise.all(
      group.playlistIds.map(async (pid) => {
        const tracks = await getPlaylistTracksClient(session.accessToken!, pid);
        const durationMs = tracks.reduce((sum, t) => sum + t.duration_ms, 0);
        return { id: pid, count: tracks.length, durationMs };
      })
    ).then((results) => {
      const map = new Map<string, PlaylistStat>();
      results.forEach(({ id: pid, count, durationMs }) => {
        map.set(pid, { count, durationMs });
      });
      setPlaylistStats(map);
      setLoadingStats(false);
    }).catch(() => setLoadingStats(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session, group]);

  const saveRules = (rules: Rule[]) => {
    const all = loadGroupedPlaylists();
    const updated = all.map((p) => (p.id === id ? { ...p, rules } : p));
    saveGroupedPlaylists(updated);
    setPlaylist((prev) => prev ? { ...prev, rules } : prev);
  };

  const generate = async () => {
    if (!playlist || !group || !session?.accessToken) return;
    setGenerating(true);
    try {
      const rawByPlaylist = await Promise.all(
        group.playlistIds.map(async (pid) => ({
          playlistId: pid,
          tracks: await getPlaylistTracksClient(session.accessToken!, pid),
        }))
      );

      // Build feature map on the flat pre-round-robin pool so BPM sort can use it
      const needsAudio = playlist.rules.some(
        (r) =>
          (r.type === "sort" && (r.method === "bpm-asc" || r.method === "bpm-desc")) ||
          r.type === "audio_feature"
      );
      let featureMap: Map<string, TrackFeature> | null = null;
      if (needsAudio) {
        const allTracks = rawByPlaylist.flatMap((p) => p.tracks);
        const features = await fetchAudioFeatures(allTracks);
        featureMap = new Map(allTracks.map((t, i) => [trackKey(t), features[i]]));
      }

      // Sort rules operate on the full combined pool so a single shuffle (or
      // any other sort) considers all tracks together. Then re-split into
      // per-playlist queues (preserving the new combined order) so round-robin
      // draws tracks in the sorted order from each playlist.
      const allTracks = rawByPlaylist.flatMap((p) => p.tracks);
      const trackPlaylist = new Map<SimplifiedTrack, string>();
      rawByPlaylist.forEach(({ playlistId, tracks }) =>
        tracks.forEach((t) => trackPlaylist.set(t, playlistId))
      );

      let sortedPool: SimplifiedTrack[] = [...allTracks];
      for (const rule of playlist.rules) {
        if (rule.type === "sort") sortedPool = applySort(sortedPool, rule, featureMap);
      }

      const sortedByPlaylist = rawByPlaylist.map(({ playlistId }) => ({
        playlistId,
        tracks: sortedPool.filter((t) => trackPlaylist.get(t) === playlistId),
      }));

      let result = applyRoundRobin(sortedByPlaylist, playlist.rules);

      // Spacing and audio feature rules refine the combined result
      for (const rule of playlist.rules) {
        if (rule.type === "spacing") result = applySpacing(result, rule);
        else if (rule.type === "audio_feature" && featureMap) result = applyAudioFeature(result, rule, featureMap);
      }
      setGenerated(result);
      try {
        localStorage.setItem(`road-trip-mix:generated:${id}`, JSON.stringify(result));
      } catch {}
    } finally {
      setGenerating(false);
    }
  };

  const sync = async () => {
    if (!generated || !playlist || !session?.accessToken) return;
    setSyncing(true);
    setSyncError(null);
    try {
      const { playlistId } = await pushToSpotify(
        session.accessToken,
        generated,
        playlist.name,
        playlist.spotifyPlaylistId
      );
      const lastSyncedAt = new Date().toISOString();
      const all = loadGroupedPlaylists();
      const updated = all.map((p) =>
        p.id === id ? { ...p, spotifyPlaylistId: playlistId, lastSyncedAt } : p
      );
      saveGroupedPlaylists(updated);
      setPlaylist((prev) => prev ? { ...prev, spotifyPlaylistId: playlistId, lastSyncedAt } : prev);
    } catch (e) {
      setSyncError(e instanceof Error ? e.message : "Sync failed.");
    } finally {
      setSyncing(false);
    }
  };

  if (!playlist) {
    return (
      <div className="px-6 py-6">
        <p style={{ color: "var(--text-subdued)" }}>Playlist not found.</p>
      </div>
    );
  }

  const totalStats = playlistStats && group
    ? group.playlistIds.reduce(
        (acc, pid) => {
          const s = playlistStats.get(pid);
          return s ? { count: acc.count + s.count, durationMs: acc.durationMs + s.durationMs } : acc;
        },
        { count: 0, durationMs: 0 }
      )
    : null;

  return (
    <div className="px-6 py-6">
      {showRules && (
        <RulesModal
          playlist={playlist}
          groupPlaylists={groupPlaylists}
          onSave={saveRules}
          onClose={() => setShowRules(false)}
        />
      )}

      <div className="playlist-content">
        {/* Header */}
        <div className="playlist-header px-8 pt-8 pb-6" style={{ position: "relative" }}>
          <div className="playlist-header-bg" />
          <div style={{ position: "relative" }}>
          <Link href="/" className="back-link text-sm mb-6 inline-block transition-colors hover:text-white">
            ← Back
          </Link>
          <div className="flex gap-6 items-end mt-4">
            <div
              className="flex-shrink-0 rounded flex items-center justify-center"
              style={{ width: 232, height: 232, background: "linear-gradient(135deg, #1a1a2e, #0f3460)", position: "relative" }}
            >
              {playlistStats && totalStats && group ? (
                <DonutChart
                  segments={group.playlistIds.map((pid, i) => ({
                    value: playlistStats.get(pid)?.durationMs ?? 0,
                    color: SEGMENT_COLORS[i % SEGMENT_COLORS.length],
                  }))}
                  totalLabel={formatTotalDuration(totalStats.durationMs)}
                  subtotalLabel={`${totalStats.count} songs`}
                  size={232}
                />
              ) : (
                <svg viewBox="0 0 24 24" width="80" height="80" fill="rgba(255,255,255,0.2)">
                  <path d="M12 3v10.55A4 4 0 1 0 14 17V7h4V3h-6z"/>
                </svg>
              )}
            </div>
            <div className="pb-2">
              <p className="playlist-label text-xs font-bold uppercase tracking-widest mb-2">
                Grouped Playlist
              </p>
              <h1 className="playlist-title font-black mb-4">{playlist.name}</h1>
              {group && (
                <p className="playlist-description text-sm mb-2">
                  Sourced from group &ldquo;{group.name}&rdquo;
                </p>
              )}

              {/* Per-playlist stats */}
              {group && (
                <div className="grouped-playlist-stats">
                  {loadingStats && !playlistStats && (
                    <p className="grouped-playlist-stats__loading">Loading stats…</p>
                  )}
                  {playlistStats && (
                    <>
                      {group.playlistIds.map((pid, i) => {
                        const stat = playlistStats.get(pid);
                        if (!stat) return null;
                        const name = groupPlaylists.find((p) => p.id === pid)?.name ?? pid;
                        return (
                          <p key={pid} className="grouped-playlist-stats__row">
                            <span
                              className="grouped-playlist-stats__dot"
                              style={{ background: SEGMENT_COLORS[i % SEGMENT_COLORS.length] }}
                            />
                            <span className="grouped-playlist-stats__name">{name}</span>
                            <span className="grouped-playlist-stats__meta">
                              {stat.count} song{stat.count !== 1 ? "s" : ""} · {formatTotalDuration(stat.durationMs)}
                            </span>
                          </p>
                        );
                      })}
                      {totalStats && group.playlistIds.length > 1 && (
                        <p className="grouped-playlist-stats__total">
                          {totalStats.count} songs total · {formatTotalDuration(totalStats.durationMs)}
                        </p>
                      )}
                    </>
                  )}
                </div>
              )}

              <p className="playlist-owner text-sm font-semibold" style={{ marginTop: playlistStats ? "12px" : undefined }}>
                {playlist.rules.length} rule{playlist.rules.length !== 1 ? "s" : ""}
                {generated && (
                  <span className="playlist-owner-sub font-normal">
                    {" "}· {generated.length} tracks generated
                  </span>
                )}
              </p>
            </div>
          </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-3 px-8 pb-6">
          <button
            onClick={() => setShowRules(true)}
            className="px-5 py-2 rounded-full text-sm font-semibold border transition-colors"
            style={{ borderColor: "rgba(255,255,255,0.3)", color: "var(--text-base)" }}
          >
            Manage Rules
          </button>
          {playlist.rules.length > 0 && (
            <button
              onClick={generate}
              disabled={generating}
              className="px-5 py-2 rounded-full text-sm font-semibold transition-opacity"
              style={{ backgroundColor: "var(--text-bright-accent)", color: "#000", opacity: generating ? 0.6 : 1 }}
            >
              {generating ? "Generating…" : generated !== null ? "Regenerate" : "Generate"}
            </button>
          )}
          {generated !== null && (
            <button
              onClick={() => {
              setGenerated(null);
              try { localStorage.removeItem(`road-trip-mix:generated:${id}`); } catch {}
            }}
              className="px-5 py-2 rounded-full text-sm font-semibold border transition-colors"
              style={{ borderColor: "rgba(255,255,255,0.2)", color: "var(--text-subdued)" }}
            >
              Clear
            </button>
          )}
          {generated !== null && generated.length > 0 && (
            <button
              onClick={sync}
              disabled={syncing}
              className="px-5 py-2 rounded-full text-sm font-semibold transition-opacity"
              style={{ backgroundColor: "#1db954", color: "#000", opacity: syncing ? 0.6 : 1 }}
            >
              {syncing ? "Syncing…" : playlist.spotifyPlaylistId ? "Update Spotify Playlist" : "Push to Spotify"}
            </button>
          )}
        </div>

        {/* Sync status */}
        {(playlist.spotifyPlaylistId || syncError) && (
          <div className="px-8 pb-4 text-xs" style={{ color: "var(--text-subdued)" }}>
            {syncError ? (
              <span style={{ color: "#e25f5f" }}>{syncError}</span>
            ) : playlist.spotifyPlaylistId && (
              <span>
                Linked to Spotify
                {playlist.lastSyncedAt && ` · Last synced ${timeSince(playlist.lastSyncedAt)}`}
                {" · "}
                <a
                  href={`https://open.spotify.com/playlist/${playlist.spotifyPlaylistId}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "#1db954", textDecoration: "underline" }}
                >
                  Open in Spotify ↗
                </a>
                {" · "}One-way sync — changes made in Spotify will be overwritten on next update.
              </span>
            )}
          </div>
        )}

        {/* Track list */}
        <div className="sp-track-list">
          {generated === null ? (
            <div className="py-12 text-center" style={{ color: "var(--text-subdued)" }}>
              {playlist.rules.length === 0
                ? "Add rules to generate a track list."
                : "Click Generate to build the track list."}
            </div>
          ) : generated.length === 0 ? (
            <div className="py-12 text-center" style={{ color: "var(--text-subdued)" }}>
              No tracks found in the source playlists.
            </div>
          ) : (
            <>
              {/* Header row */}
              <div className="sp-track-header">
                <span className="sp-track-header__num">#</span>
                <span>Title</span>
                <span>Album</span>
                <span>Source</span>
                <span className="sp-track-header__dur">
                  <svg viewBox="0 0 16 16" width="14" height="14" fill="currentColor">
                    <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
                  </svg>
                </span>
              </div>

              {generated.map((track, i) => {
                const cumulative = generated.slice(0, i + 1).reduce((s, t) => s + t.duration_ms, 0);
                const sourceName = groupPlaylists.find((p) => p.id === track.sourcePlaylistId)?.name ?? track.sourcePlaylistId ?? "";
                const sourceColor = SEGMENT_COLORS[
                  (group?.playlistIds.indexOf(track.sourcePlaylistId) ?? 0) % SEGMENT_COLORS.length
                ];
                const artUrl = track.album.images[0]?.url;
                return (
                  <div key={track.id + i} className="sp-track-row">
                    <span className="sp-track-row__num">{i + 1}</span>

                    <div className="sp-track-row__title">
                      {artUrl
                        ? <img src={artUrl} alt="" width={40} height={40} className="sp-track-art" />
                        : <div className="sp-track-art" />
                      }
                      <div className="sp-track-name-artist">
                        <p className="sp-track-name">{track.name}</p>
                        <p className="sp-track-artist">{track.artists.map((a) => a.name).join(", ")}</p>
                      </div>
                    </div>

                    <span className="sp-track-col">{track.album.name}</span>

                    <div className="sp-track-source sp-track-col">
                      <span style={{ width: 8, height: 8, borderRadius: "50%", background: sourceColor, flexShrink: 0, display: "inline-block" }} />
                      <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{sourceName}</span>
                    </div>

                    <div className="sp-track-dur">
                      <p className="sp-track-dur__main">{formatDuration(track.duration_ms)}</p>
                      <p className="sp-track-dur__cumul">{formatTotalDuration(cumulative)}</p>
                    </div>
                  </div>
                );
              })}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
